apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-incident-triage.fullname" . }}
  labels:
    {{- include "k8s-incident-triage.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "k8s-incident-triage.selectorLabels" . | nindent 4 }}
